name: Publicador Radar

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # FORZAMOS PYTHON 3.10 (El 3.9 da error con Gemini Flash)
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
          
      # FORZAMOS ACTUALIZACIÓN DE LIBRERÍAS
      - name: Instalar Herramientas
        run: pip install --upgrade --force-reinstall feedparser google-generativeai google-auth google-api-python-client requests

      - name: Ejecutar Robot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        run: python main.py
