name: Publicador Radar

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # CAMBIO IMPORTANTE: Usamos Python 3.10
      - name: Python Setup
        uses: actions/setup-python@v4 
        with:
          python-version: '3.10'
          
      - name: Instalar
        run: pip install -U feedparser google-generativeai google-auth google-api-python-client requests

      - name: Ejecutar
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        run: python main.py
