name: Publicador Radar

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      # INSTALAMOS SOLO LO NECESARIO (Sin la librer√≠a de IA que falla)
      - name: Instalar Herramientas
        run: pip install feedparser google-auth google-api-python-client requests

      - name: Ejecutar Robot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        run: python main.py
