name: Publicador Radar

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Versión ideal para la nueva librería
          
      - name: Instalar Herramientas
        # AQUÍ ESTÁ EL CAMBIO: instalamos 'google-genai'
        run: pip install feedparser google-genai google-auth google-api-python-client

      - name: Ejecutar Robot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        run: python main.py
